import type { Cipher } from 'node:crypto'

export interface IEncipher extends Cipher {
  /**
   * Get the authentication tag (also known as an "auth tag" or simply "tag").
   *
   * The authentication tag is a fixed-length value that is generated by the encryption process and
   * used to ensure the authenticity and integrity of the encrypted data.
   */
  getAuthTag?(): Buffer
}
