[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
version = "0.1.1"
edition = "2024"
rust-version = "1.96"
license = "MIT"
repository = "https://github.com/guanghechen/sora"
homepage = "https://github.com/guanghechen/sora/tree/rust"
publish = true

[workspace.lints.rust]
unsafe_code = "forbid"
