import { execFileSync } from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'

export const HOOKS_DIR = '.githooks'

const GENERATED_HEADER =
  '# AUTO-GENERATED by @guanghechen/githooks. Edit the "githooks" field in package.json instead.'

/**
 * Detect whether the process runs inside a CI environment.
 * Covers the common `CI` flag (GitHub Actions / GitLab / CircleCI / Travis, etc.) plus a few
 * vendor-specific variables, while treating the falsy string values as "not CI".
 *
 * @param {Record<string, string | undefined>} [env]
 * @returns {boolean}
 */
export function isCI(env = process.env) {
  const ci = env.CI
  if (ci && ci !== 'false' && ci !== '0') return true
  return Boolean(env.CONTINUOUS_INTEGRATION || env.GITHUB_ACTIONS || env.BUILD_NUMBER)
}

/**
 * Render a POSIX `sh` hook script that runs the given command and honors the `GITHOOKS=0` bypass.
 *
 * @param {string} command
 * @returns {string}
 */
export function renderHookScript(command) {
  return [
    '#!/usr/bin/env sh',
    GENERATED_HEADER,
    // eslint-disable-next-line no-template-curly-in-string -- intentional POSIX sh parameter expansion
    '[ "${GITHOOKS-}" = "0" ] && exit 0',
    command,
    '',
  ].join('\n')
}

/**
 * Whether `name` is a safe, bare git-hook filename (no path separators / traversal).
 *
 * @param {string} name
 * @returns {boolean}
 */
export function isValidHookName(name) {
  if (name === '' || name === '.' || name === '..') return false
  return !name.includes('/') && !name.includes('\\') && !name.includes('\0')
}

/**
 * Read and normalize the `githooks.hooks` map declared in the package.json under `cwd`.
 * Non-string, blank, or unsafe-named entries are dropped.
 *
 * @param {string} [cwd]
 * @returns {Record<string, string>}
 */
export function resolveHooksConfig(cwd = process.cwd()) {
  const manifestPath = path.resolve(cwd, 'package.json')
  const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'))
  const hooks = manifest.githooks?.hooks
  /** @type {Record<string, string>} */
  const result = {}
  if (hooks && typeof hooks === 'object') {
    for (const [name, command] of Object.entries(hooks)) {
      if (typeof command === 'string' && command.trim().length > 0 && isValidHookName(name)) {
        result[name] = command
      }
    }
  }
  return result
}

/**
 * @param {import('./index.d.ts').IGithooksOptions} options
 * @returns {{ cwd: string, env: Record<string, string | undefined>, logger: { info(message: string): void } }}
 */
function normalize(options) {
  return {
    cwd: options.cwd ?? process.cwd(),
    env: options.env ?? process.env,
    logger: options.logger ?? console,
  }
}

/**
 * Resolve the git work tree's top-level directory, so hooks are always anchored where git looks
 * for a relative `core.hooksPath` — regardless of which subdirectory the caller ran from.
 *
 * @param {string} cwd
 * @returns {string} the toplevel path, or an empty string when `cwd` is not inside a git work tree.
 */
function gitToplevel(cwd) {
  try {
    return execFileSync('git', ['rev-parse', '--show-toplevel'], { cwd, encoding: 'utf8' }).trim()
  } catch {
    return ''
  }
}

/**
 * @param {string} cwd
 * @returns {string} the configured `core.hooksPath`, or an empty string when unset.
 */
function readHooksPath(cwd) {
  try {
    return execFileSync('git', ['config', '--get', 'core.hooksPath'], {
      cwd,
      encoding: 'utf8',
    }).trim()
  } catch {
    return ''
  }
}

/**
 * @param {string} p
 * @returns {import('node:fs').Stats | null} lstat of `p` (does not follow symlinks), or null if absent.
 */
function lstatOrNull(p) {
  try {
    return fs.lstatSync(p)
  } catch {
    return null
  }
}

/**
 * Delete only the regular hook files this tool generated (identified by the header), leaving
 * foreign files, symlinks, and subdirectories in `hooksDir` untouched (symlinks are never followed).
 *
 * @param {string} hooksDir
 * @returns {void}
 */
function removeGeneratedHookFiles(hooksDir) {
  let entries
  try {
    entries = fs.readdirSync(hooksDir)
  } catch {
    return
  }
  for (const name of entries) {
    const file = path.join(hooksDir, name)
    if (fs.lstatSync(file).isFile() && fs.readFileSync(file, 'utf8').includes(GENERATED_HEADER)) {
      fs.rmSync(file, { force: true })
    }
  }
}

/**
 * Generate the configured hooks into `<git-root>/.githooks/` and point git at them via
 * `core.hooksPath`. Hooks are anchored at the git top-level (not the caller's cwd) so they fire no
 * matter which subdirectory install ran from. No-op (returns false) in CI or outside a git work tree.
 *
 * @param {import('./index.d.ts').IGithooksOptions} [options]
 * @returns {boolean} whether hooks were installed.
 */
export function installHooks(options = {}) {
  const { cwd, env, logger } = normalize(options)
  if (isCI(env)) {
    logger.info('[githooks] CI detected, skip installing git hooks.')
    return false
  }
  const root = gitToplevel(cwd)
  if (!root) {
    logger.info('[githooks] not a git work tree, skip installing git hooks.')
    return false
  }

  const hooks = resolveHooksConfig(root)
  const names = Object.keys(hooks)
  const hooksDir = path.resolve(root, HOOKS_DIR)

  fs.mkdirSync(hooksDir, { recursive: true })
  removeGeneratedHookFiles(hooksDir)
  /** @type {string[]} */
  const written = []
  for (const name of names) {
    const file = path.join(hooksDir, name)
    if (lstatOrNull(file)) {
      logger.info(`[githooks] refusing to overwrite existing "${name}"; leaving it untouched.`)
      continue
    }
    fs.writeFileSync(file, renderHookScript(hooks[name]), { mode: 0o755 })
    fs.chmodSync(file, 0o755)
    written.push(name)
  }
  execFileSync('git', ['config', 'core.hooksPath', HOOKS_DIR], { cwd: root, stdio: 'ignore' })

  logger.info(
    `[githooks] installed ${written.length} hook(s)${written.length ? `: ${written.join(', ')}` : ''} -> ${HOOKS_DIR}/`,
  )
  return true
}

/**
 * Reverse {@link installHooks}: only when `core.hooksPath` points at our `.githooks`, unset it and
 * delete the hook files we generated (preserving any foreign files), then remove the dir if empty.
 *
 * @param {import('./index.d.ts').IGithooksOptions} [options]
 * @returns {boolean}
 */
export function uninstallHooks(options = {}) {
  const { cwd, logger } = normalize(options)
  const root = gitToplevel(cwd)
  if (!root) {
    logger.info('[githooks] not a git work tree, nothing to uninstall.')
    return false
  }
  if (readHooksPath(root) !== HOOKS_DIR) {
    logger.info('[githooks] core.hooksPath is not managed by githooks; leaving it untouched.')
    return false
  }
  execFileSync('git', ['config', '--unset', 'core.hooksPath'], { cwd: root, stdio: 'ignore' })
  const hooksDir = path.resolve(root, HOOKS_DIR)
  removeGeneratedHookFiles(hooksDir)
  try {
    fs.rmdirSync(hooksDir)
  } catch {
    // dir still holds foreign files, or was already gone — leave it
  }
  logger.info('[githooks] uninstalled git hooks.')
  return true
}

/**
 * Print the configured hooks and the current `core.hooksPath`.
 *
 * @param {import('./index.d.ts').IGithooksOptions} [options]
 * @returns {Record<string, string>}
 */
export function listHooks(options = {}) {
  const { cwd, logger } = normalize(options)
  const root = gitToplevel(cwd) || cwd
  const hooks = resolveHooksConfig(root)
  logger.info(`[githooks] core.hooksPath = ${readHooksPath(root) || '(unset)'}`)
  for (const [name, command] of Object.entries(hooks)) {
    logger.info(`[githooks]   ${name}: ${command}`)
  }
  return hooks
}
