[package]
name = "guanghechen-reporter"
description = "Thread-safe level-based reporting foundation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true

[dependencies]
guanghechen-chalk = { path = "../chalk", version = "=0.1.0" }

[lints]
workspace = true
